const assert = require('assert')
const isPowerOfTwo = require('../isPowerOfTwo')

describe('isPowerOfTwo', () => {
  it('should check if the number is made by multiplying twos', () => {
    assert.equal(isPowerOfTwo(-1), false)
    assert.equal(isPowerOfTwo(0), false)
    assert.equal(isPowerOfTwo(1), true)
    assert.equal(isPowerOfTwo(2), true)
    assert.equal(isPowerOfTwo(3), false)
    assert.equal(isPowerOfTwo(4), true)
    assert.equal(isPowerOfTwo(5), false)
    assert.equal(isPowerOfTwo(6), false)
    assert.equal(isPowerOfTwo(7), false)
    assert.equal(isPowerOfTwo(8), true)
    assert.equal(isPowerOfTwo(10), false)
    assert.equal(isPowerOfTwo(12), false)
    assert.equal(isPowerOfTwo(16), true)
    assert.equal(isPowerOfTwo(31), false)
    assert.equal(isPowerOfTwo(64), true)
    assert.equal(isPowerOfTwo(1024), true)
    assert.equal(isPowerOfTwo(1023), false)
  })
})